name: Build

on:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  build:
    name: "Publish POM"
    runs-on: ubuntu-latest
    env:
      SIGNING_KEY_ID: 40D4E7C6
      OSSRH_USERNAME: mjstrasser

    steps:
      - name: Check out code
        uses: actions/checkout@v2.3.5
        with:
          fetch-depth: 0

      - name: Publish POM
        run: ./gradlew publish
        env:
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
